{{- /* SPDX-License-Identifier: Apache-2.0 */ -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hw-fault-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hw-fault-exporter.labels" . | nindent 4 }}
