blank_issues_enabled: false
contact_links:
  - name: Hardware questions
    url: https://github.com/hanna-hawa/fault-oracle/discussions
    about: Ask questions about specific hardware or board support here.
